### ISSUE TITLE
Mouseout only when leaving layer area

### ISSUE THREAD

**Issue by prebm** [danzel/Leaflet.utfgrid#32]
Is there a reason why the mouseout functionality in the example is in the mouseover-function? 

```javascript
utfGrid.on('mouseover', function (e) {
if (e.data) {
    document.getElementById('hover').innerHTML = 'hover: ' + e.data.admin;
} else {
    // works like mouseout
    document.getElementById('hover').innerHTML = 'hover: nothing';
}
//console.log('mouseover: ' + e.data);
});
```

I had a problem with triggering the mouseout too often, while the code in the example didn't work well. Then I changed the mouseout to 

```javascript
if (this._mouseOn && on.data == null) { // the new part '&& on.data == null'
    this.fire('mouseout', { latlng: e.latlng, data: this._mouseOn });
    if (this.options.pointerCursor) {
        this._container.style.cursor = '';
    }
}
```

and now the mouseout is triggered when leaving the layer or hovering over a region with no values. Could there be any problems with it?

**Comment by danzel** [comment]
Dunno, just works a different way.

**Comment by prebm** [comment]
Would it be worth to prepare a pull request to include this part in the code?

**Comment by danzel** [comment]
Yeah, we should probably make it behave that when the mouse is on a ```data == null``` area we generate a mouseout.

**Comment by prebm** [comment]
Ok, created a pull request.
